// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies";
    extern const char* const UnityCopyright = "(c) 2005-2023 Unity Technologies. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2021.3.25f1";
    extern const char* const UnityVersionDigits = "2021.3.25";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2021;
    extern const UInt32 UnityVersionMajor = 3;
    extern const UInt32 UnityVersionMinor = 25;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2021.3.25f1_68ef2c4f8861";
    extern const char* const UnityVersionUnderHash_Verbose = "2021.3.25f1_68ef2c4f8861";
    extern const char* const UnityVersionUnderHash_WithParens = "2021.3.25f1 (68ef2c4f8861)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 6876972;

    extern const UInt64 UnityVersionDate = 1682967931;
    extern const char* const UnityVersionBranch = "2021.3/staging";
    extern const char* const UnityVersionDisplay = "2021.3.25f1";
    extern const char* const UnityVersionDisplay_Verbose = "2021.3.25f1.git.6876972";
    extern const char* const UnityVersionRevision = "68ef2c4f8861";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2021.3.25f1 (68ef2c4f8861)";
    extern const wchar_t* const L_UnityVersion = L"2021.3.25f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies"
    #define UNITY_COPYRIGHT "(c) 2005-2023 Unity Technologies. All rights reserved."
    #define UNITY_VERSION_VER 2021
    #define UNITY_VERSION_MAJ 3
    #define UNITY_VERSION_MIN 25
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2021.3.25f1_68ef2c4f8861"
    #define UNITY_VERSION_PARENS_HASH "2021.3.25f1 (68ef2c4f8861)"
    #define UNITY_VERSION_BLD 6876972
    #define UNITY_VERSION_WIN "2021.3.25.6876972"

#endif // !RC_INVOKED
